### ISSUE TITLE
RequestMessage RequestId always returns a different value

### ISSUE THREAD

**Issue by ChrisMiskowiec** [FlorianHockmann/Gremlin.Net#10]
RequestMessage.RequestId returns Guid.NewGuid(); this causes a different ID to be generated any time you call the property getter. For example, I was trying to log request and response IDs, but the value was different every time I inspected it.

I think the value should be assigned during construction, and that value returned, so that it's the same throughout the lifetime of the request. For example:

```cs
private readonly Guid _requestId = Guid.NewGuid();

[JsonProperty(PropertyName = "requestId")]
public Guid RequestId => _requestId;
```

Also, I'm unable to find a reference on this, but I have seen in other implementations that the authentication message uses the same request ID as the original request. This makes sense to me, as it is part of the same logical request.

**Comment by FlorianHockmann** [comment]
> RequestMessage.RequestId returns Guid.NewGuid(); this causes a different ID to be generated any time you call the property getter. For example, I was trying to log request and response IDs, but the value was different every time I inspected it.

Yes, I see that this causes confusion. To be honest I only made the getter public because I wanted to ensure with a unit test that two request messages get different request IDs. But of course when the getter is public then accessing it should really return the request ID that will be sent to the server. So I will use the fix you proposed.

In general though the request IDs are completely meaningless for Gremlin.Net. Their sole purpose is to allow the client to find the right request message for a received response. This is necessary because the client can send multiple requests in parallel over the same WebSocket connection.
But the `System.Net.WebSocket` class Gremlin.Net uses does not support sending multiple requests in parallel over the same WebSocket:

> Exactly one send and one receive is supported on each WebSocket object in parallel.

(Source: https://docs.microsoft.com/de-de/dotnet/api/system.net.websockets.websocket.sendasync)

So Gremlin.Net won't reuse the same connection until all data is received from the previous request. Therefore the request IDs aren't needed at all since it's always clear to which request a response belongs to. (This also made the implementation a lot easier by the way.)

Since request IDs are only meant for this purpose it makes also sense that the Gremlin Server doesn't check whether the request ID of an authentication response is the same as the request ID from the original request. So there is no need for Gremlin.Net to reuse the original request ID for the authentication response.

**Comment by FlorianHockmann** [comment]
I'm closing this as it should be resolved by the linked commit. Feel free to re-open if you want to add something.
