### ISSUE TITLE
target .net standard

### ISSUE THREAD

**Issue by grahamehorner** [FlorianHockmann/Gremlin.Net#6]
please consider targeting .net standard, given the GA of Azure Cosmos DB this allow using the library of a number of hardware/software platforms

**Comment by FlorianHockmann** [comment]
I am not sure what you mean exactly. Gremlin.Net targets already .NET Standard 1.3.

**Comment by aaronlangford31** [comment]
It sounds like grahamehorner may be talking about something related to an issue I am trying to get around. When trying to install this package in Nuget, I get the following error:

`Could not install package 'Gremlin.Net 0.1.3'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

**Comment by FlorianHockmann** [comment]
@aaronlangford31 Unfortunately, Gremlin.Net cannot work with .NET Framework 4.5 because it relies on `System.Net.WebSockets` to communicate with Gremlin Server and `System.Net.WebSockets` targets .NET Framework 4.6 and .NET Standard 1.3: https://www.nuget.org/packages/System.Net.WebSockets/
So you probably have to update your project to .NET Framework 4.6 (or .NET Core) when you want to use Gremlin.Net.

**Comment by ChrisMiskowiec** [comment]
@FlorianHockmann Your code does work on .NET Framework 4.5+... the System.Net.WebSockets namespace exists in System.dll since 4.5. I have been able to clone your repo and target 4.5, and it all works (with slight modifications for how configuration & NuGet packages are used). However your NuGet package only targets .NET Standard, so it cannot be added to a .NET Framework project. 

I don't know enough about NuGet packages to do a pull request at this time, but I thought you should know all the code works fine under .NET Framework.

**Comment by FlorianHockmann** [comment]
@ChrisMiskowiec You can definitely use the Gremlin.Net NuGet package in a .NET Framework project.
The problem you and @aaronlangford31 seem to have is that you are using .NET Framework 4.5 which only supports .NET Standard 1.1 (or 1.2 if you are using .NET Framework 4.5.1) and Gremlin.Net targets .NET Standard 1.3.
But since `System.Net.WebSockets` was already part of .NET Framework 4.5 as you mentioned, it should be possible to add that as a target framework to Gremlin.Net. I created a new issue for that: #9.

I am closing this issue now as it is unclear what it is about since Gremlin.Net already targets .NET Standard like it is asked for in the title of this issue. @grahamehorner When you meant something else, then just re-open the issue and describe what you meant exactly.
